### ISSUE TITLE
make some function destructive

### ISSUE THREAD

**Issue by futurist** [magnars/s.el#105]
I found it's no pros to use some s- functions compare to native ones, like: `s-append` compare to `concat`

Like some elisp functions, like `sort` `ncons`, people use it for it's simplify the modification.

So my proposal is to make some functions (maybe new ones) with modification feature, like:

```lisp
(s-append-it ";" s)  ; will modify s
```

That way user can enjoy it than using native one: `(setq s (concat s ";"))`

**Comment by jasonm23** [comment]
Closing as not to be implemented.
