### ISSUE TITLE
Document that s-lex-format is a macro

### ISSUE THREAD

**Issue by ilitzroth** [magnars/s.el#118]
I also don't quite get why it is a macro. this function used with s-format is what I expected:

(defun s-format-helper (var-name)
  (let ((symbol (intern var-name)))
    (if (boundp symbol)
        (symbol-value symbol)
      (error "symbol %s has no value" var-name))))

**Comment by Fuco1** [comment]
I guess it's a macro for performance reasons, the intern is only done once during macro expansion.  Not that it makes any real difference, but maybe in a tight loop it might save some time.
