### ISSUE TITLE
Tests fail against Emacs 26.1

### ISSUE THREAD

**Issue by spwhitton** [magnars/s.el#130]
Debian is transitioning from Emacs 25.2 to Emacs 26.1 and we observed that s-el's test suite fails against Emacs 26:

    Ran 66 tests, 39 results as expected, 27 unexpected (2018-12-18 19:08:41+0000)

    27 unexpected results:
       FAILED  s-capitalized-words
       FAILED  s-collapse-whitespace
       FAILED  s-count-matches
       FAILED  s-dashed-words
       FAILED  s-format
       FAILED  s-lex-format
       FAILED  s-lines
       FAILED  s-lower-camel-case
       FAILED  s-match
       FAILED  s-match-strings-all
       FAILED  s-matched-positions-all
       FAILED  s-replace
       FAILED  s-replace-all
       FAILED  s-reverse
       FAILED  s-slice-at
       FAILED  s-snake-case
       FAILED  s-split
       FAILED  s-split-up-to
       FAILED  s-split-words
       FAILED  s-titleized-words
       FAILED  s-trim
       FAILED  s-trim-left
       FAILED  s-trim-right
       FAILED  s-upper-camel-case
       FAILED  s-with
       FAILED  s-word-initials
       FAILED  s-word-wrap

[A full log is downloadable from here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916810).

**Comment by magnars** [comment]
I just installed Emacs 26.1 and ran the tests, and they all ran fine. Any idea how I can reproduce this issue?

**Comment by spwhitton** [comment]
Hello Magnar,

On Sun 23 Dec 2018 at 01:35am -0800, Magnar Sveen wrote:

> I just installed Emacs 26.1 and ran the tests, and they all ran
> fine. Any idea how I can reproduce this issue?

Since filing this bug I have found that I can only reproduce the issue
in batch mode (i.e. emacs -batch), not in interactive mode.  And,
further, only when I use `emacs -Q -batch`, not `emacs -q -batch`.

I would be interested to hear if you can reproduce the issue using
`emacs -Q batch`.

-- 
Sean Whitton

**Comment by magnars** [comment]
```
➜  s.el git:(master) emacs -Q -batch -l dev/ert.el -l dev/examples-to-tests.el -l s.el -l dev/examples.el -f ert-run-tests-batch-and-exit
dev/ert.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.
dev/ert.el: ‘labels’ is an obsolete macro (as of 24.3); use ‘cl-labels’ instead.
dev/ert.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.
Running 67 tests (2018-12-23 21:36:27+0100)
   passed   1/67  s-append
   passed   2/67  s-blank-str\?
   passed   3/67  s-blank\?
   passed   4/67  s-capitalize
   passed   5/67  s-capitalized-words
   passed   6/67  s-capitalized\?
   passed   7/67  s-center
   passed   8/67  s-chomp
   passed   9/67  s-chop-prefix
   passed  10/67  s-chop-prefixes
   passed  11/67  s-chop-suffix
   passed  12/67  s-chop-suffixes
   passed  13/67  s-collapse-whitespace
   passed  14/67  s-concat
   passed  15/67  s-contains\?
   passed  16/67  s-count-matches
   passed  17/67  s-dashed-words
   passed  18/67  s-downcase
   passed  19/67  s-ends-with\?
   passed  20/67  s-equals\?
   passed  21/67  s-format
   passed  22/67  s-index-of
   passed  23/67  s-join
   passed  24/67  s-left
   passed  25/67  s-less\?
   passed  26/67  s-lex-format
   passed  27/67  s-lines
   passed  28/67  s-lower-camel-case
   passed  29/67  s-lowercase\?
   passed  30/67  s-match
   passed  31/67  s-match-strings-all
   passed  32/67  s-matched-positions-all
   passed  33/67  s-matches\?
   passed  34/67  s-mixedcase\?
   passed  35/67  s-numeric\?
   passed  36/67  s-pad-left
   passed  37/67  s-pad-right
   passed  38/67  s-prepend
   passed  39/67  s-presence
   passed  40/67  s-present\?
   passed  41/67  s-repeat
   passed  42/67  s-replace
   passed  43/67  s-replace-all
   passed  44/67  s-replace-regexp
   passed  45/67  s-reverse
   passed  46/67  s-right
   passed  47/67  s-shared-end
   passed  48/67  s-shared-start
   passed  49/67  s-slice-at
   passed  50/67  s-snake-case
   passed  51/67  s-split
   passed  52/67  s-split-up-to
   passed  53/67  s-split-words
   passed  54/67  s-starts-with\?
   passed  55/67  s-titleize
   passed  56/67  s-titleized-words
   passed  57/67  s-trim
   passed  58/67  s-trim-left
   passed  59/67  s-trim-right
   passed  60/67  s-truncate
   passed  61/67  s-upcase
   passed  62/67  s-upper-camel-case
   passed  63/67  s-uppercase\?
   passed  64/67  s-with
   passed  65/67  s-word-initials
   passed  66/67  s-word-wrap
   passed  67/67  s-wrap

Ran 67 tests, 67 results as expected (2018-12-23 21:36:27+0100)
```

Any further ideas?

**Comment by scfc** [comment]
When I launch a Docker container of `debian:unstable`, the package builds and the tests run fine there (uncommenting `disable = yes` in `debian/elpa-test`).

**Comment by spwhitton** [comment]
Hello,

Thank you both for your tests and your attention.  I'm not going to
re-enable the tests in Debian unstable until the source of this problem
makes itself known, but for now it seems reasonable for us to assume
it's a Debian-specific problem and close this bug.

-- 
Sean Whitton

**Comment by magnars** [comment]
I will close this issue for now. Feel free to reopen it if you find a way to reproduce it!
