### ISSUE TITLE
 s-replace-all case-issue

### ISSUE THREAD

**Issue by thisch** [magnars/s.el#138]
If the string contains a substring that is equal to one of the keys of the `replacements` alist, but with a different case, then  `Wrong type argument: stringp, nil` is output.

This is an example from #62 
```
(s-replace-all '(("BLAH" . "wah")
         ("BLOO" ."woo"))
           "BLAH BLOO BLEE")
```

which outputs 
```
"wah woo BLEE"
```

However, if the key "BLAH" is replaced by "Blah", I get the error from above

```
(s-replace-all '(("Blah" . "wah")
         ("BLOO" ."woo"))
           "BLAH BLOO BLEE")
```

**Comment by jasonm23** [comment]
@syohex any ideas on this one?  (Error tested and reproduced.)

**Comment by syohex** [comment]
Sorry I don't remember anything about this. How about using `CASE-FOLD` argument of `assoc-string` as below ?

```diff
diff --git a/s.el b/s.el
index ba6c1ed..f1dfe9c 100644
--- a/s.el
+++ b/s.el
@@ -400,7 +400,7 @@ This is a simple wrapper around the built-in `string-match-p'."
 
 (defun s--aget (alist key)
   (declare (pure t) (side-effect-free t))
-  (cdr (assoc-string key alist)))
+  (cdr (assoc-string key alist case-fold-search)))
 
 (defun s-replace-all (replacements s)
   "REPLACEMENTS is a list of cons-cells. Each `car` is replaced with `cdr` in S."
```

**Comment by jasonm23** [comment]
@syohex @magnars turns out it's a silly error, if the replacement lamba comes up with `nil` it's going to send that back to `replace-regexp-in-string`

So I've added a condition to avert the problem...

```
(defun s-replace-all (replacements s)
  "REPLACEMENTS is a list of cons-cells. Each `car` is replaced with `cdr` in S."
  (declare (pure t) (side-effect-free t))
  (replace-regexp-in-string
   (regexp-opt (mapcar 'car replacements))
   (lambda (it)
     (let ((replacement (s--aget replacements it)))
       (if (null replacement)
           it
         replacement)))
   s t t))
```

I'll push a PR tomorrow. Comments welcome.
