### ISSUE TITLE
Marmalade is dead, the document should be updated correspondingly.

### ISSUE THREAD

**Issue by hongyi-zhao** [magnars/s.el#139]
In the [installation section](https://github.com/magnars/s.el#installation), you told the following:

```
It's available on marmalade and Melpa:

M-x package-install s
```
But, in fact, the marmalade is dead according to the [notes](https://emacs.stackexchange.com/questions/10500/do-i-still-need-gnu-elpa-if-i-have-melpa/10501): 

`
Marmalade is essentially dead. The certificate has expired and there's hardly any new packages uploaded. This is due to its rather unusual process, you need to be manually added to the users by its owner and as he's gone missing, no new users have been added since 2016 or so.`

So, I think the document should be updated correspondingly.

**Comment by magnars** [comment]
Thanks!
