### ISSUE TITLE
[feature request] function to split string into cons cell

### ISSUE THREAD

**Issue by Atlas48** [magnars/s.el#141]
So, as the title says, I would like a function to split a string on it's first occurrence into a cons cell, I've provided some examples of what it might look like below.

```elisp
(s-split-cons "this:that" ":")
("this". "that")

(s-split-cons "more than one")
("more" . "than one")
``` 
I'd implement it myself, but I don't think I'd give a very clean implementation for such.

**Comment by jasonm23** [comment]
```lisp
(let* ((str "this is a test")
       (sep " ")
       (s-car (car (s-split sep str)))
       (s-cdr (substring str (length (concat s-car sep)))))
  (cons s-car s-cdr))
```

Something like this...

**Comment by jasonm23** [comment]
```lisp
(defun s-split-cons (s &optional separator)
  "Split S using SEPARATOR (defaults to space).

The return value is a `cons' cell with the first item of the
split as `car' and the rest of the string as `cdr'.

For example.

   (s-split-cons \"this:that\" \":\")
   => (\"this\" . \"that\")

   (s-split \"more than one\")
   => (\"more\" . \"than one\")
"
  (declare (side-effect-free t))
  (let* ((sep (or separator " "))
         (s-car (car (s-split separator s)))
         (s-cdr (substring s (+ 1 (length (concat s-car separator))))))
   (cons s-car s-cdr)))
```

So I'll consider the utility of this one.  It seems very niche tbh.

@Atlas48 Can you help me understand how this would be generally useful to many people.  I struggled as I wrote the docstring to think of a use-case for this.

**Comment by jasonm23** [comment]
@magnars any thoughts on this?

**Comment by magnars** [comment]
I'm generally of the opinion that we should keep the `s` api generally useful. There are a lot of features that could conceivably fit under the "string manipulation" umbrella. I'm wary of adding all of them to the bulk of code that we're maintaining.

In this specific case, I think I agree with you @jasonm23 that this seems quite niche.

**Comment by jasonm23** [comment]
I'm closing this as out of scope.
