### ISSUE TITLE
Is it dead...

### ISSUE THREAD

**Issue by jasonm23** [magnars/s.el#146]
Hi @magnars @nicferrier is s.el still being maintained.  If not is there need of help with the package?

**Comment by magnars** [comment]
Hi Jason! I would rather think of it as finished. Is there something in particular that you are missing?

**Comment by jasonm23** [comment]
I was just looking over the open issues and PRs.

I also had some things I wanted to add, but nothing ready at this point.

**Comment by jasonm23** [comment]
One thing I was thinking about in particular was improved regexp replace string, so that replacement functions can receive full match data for subexp/groups.

**Comment by magnars** [comment]
For a library like s.el, which so many other projects depend on, I find the best feature of all is stability. In my mind s has been complete for several years.

There are naturally lots of features that could reasonably be placed in s.el that it currently does not have, but for it to be a worthwhile addition it would both have to be 1) useful to a lot of people, and 2) not break any existing functionality. 

You might say that I am happy with the current state of s.el. It is useful and stable. Software doesn't need constant changes to be alive. However, if someone did want to maintain the package in a careful way, I would be open for that.

**Comment by jasonm23** [comment]
I agree completely.

Wrt to the open PRs and issues, which all look like they are stale at this point.  Did you have a plan for that?

Re: additional features I'll work on that and post a PR with tests and ensure stability.

Maintenance wise I may have bandwidth to assist with issues and PRs

**Comment by magnars** [comment]
Good to hear that we're in sync wrt stability and breaking changes. If you'd be willing to do a bit of spring cleaning in the PR/issues department, that would be great. I'm adding you as a collaborator. Cheers!

**Comment by jasonm23** [comment]
Good stuff.  I'll have a look at these issues and PRs today.

**Comment by jasonm23** [comment]
@magnars - https://travis-ci.org/github/magnars/s.el we have an issue here..

<img width="1058" alt="Screenshot 2022-08-12 at 5 09 56 PM" src="https://user-images.githubusercontent.com/71587/184333564-7e87a18d-3c9d-49ea-ba23-e00780769aaa.png">

**Comment by magnars** [comment]
I tried setting it up on travis.com, but they wanted my credit card info even for the free plan, so I bailed. I guess the bitcoin miners have ruined services such as this. I'll have to take a look at it later.

**Comment by jasonm23** [comment]
Bad news I'd have _assumed_ Travis would be the best free beer option.

Perhaps Gitlab or GitHub CIs have free tiers that don't need CCard info
