### ISSUE TITLE
🐣 [REQUEST] - add s-truncate-width

### ISSUE THREAD

**Issue by zbelial** [magnars/s.el#161]
### Summary

I'd like to propose to add a function `s-truncate-width`, which truncates a string according to width (same meaning as in `string-width`). Following is an implementation I wrote(haven't tested it thoroughly):
```elisp
(defun s-truncate-width (width s &optional ellipsis)
  (let ((idx 0)
        (idx-width 0)
        (fills "")
        (start 0)
        (end (length s))
        (loop t)
        (ellipsis (or ellipsis ?.)))
    (when (< width 0)
      (error "args out of range"))
    (if (<= (string-width s) width)
        (setq idx (length s))
      (setq idx (/ (+ start end) 2))
      (while loop
        (setq idx-width (string-width s 0 idx))
        (cond
         ((= idx-width width)
          (setq loop nil))
         ((> idx-width width)
          (setq end idx)
          (setq idx (/ (+ start end) 2)))
         ((< idx-width width)
          (if (> (string-width s 0 (1+ idx)) width)
              (setq loop nil)
            (setq start idx)
            (setq idx (/ (+ start end) 2))))))
      (setq fills (make-string (- width (string-width s 0 idx)) ellipsis)))
    (format "%s%s" (substring s 0 idx) fills)))
```

### Basic Example

;; (s-truncate-width 3 "hello") -> "hel"
;; (s-truncate-width 7 "早晨，你好") -> "早晨，."

This function is usful when you use languages like CJK and want to truncate them according to width (where `s-truncate` is not suitable), like in the following image.
![图片](https://user-images.githubusercontent.com/6436456/188362430-41ddef52-da21-4a58-a5d9-5cbeac9b278c.png)

### Drawbacks

IMO, none.

**Comment by jasonm23** [comment]
@zbelial, thank you for the feature request. I am unclear what the difference between this and `s-truncate`.  

To clarify, `s-truncate-width` is concerned with unicode character width as opposed to string length, correct?

**Comment by jasonm23** [comment]
Could you also let me know how `s-truncate-width` differs from `truncate-string-to-width`.

Thank you.

**Comment by zbelial** [comment]
Hi @jasonm23 , thanks for your quick reply.

> To clarify, `s-truncate-width` is concerned with unicode character width as opposed to string length, correct?

Yes, it's correct.

Actually I think `truncate-string-to-width` is what I was looking for, but I didn't know its existence. So `s-truncate-width` is not needed  for me, I'll close this request.

Sorry for bothering you guys and thanks again, jasonm23.
