### ISSUE TITLE
RFC : Dropping support for Emacs versions below 26.

### ISSUE THREAD

**Issue by jasonm23** [magnars/s.el#163]
### Description

According to the [Emacs Survey 2020 results](https://emacssurvey.org/2020/), ~6% of Emacs use takes place on versions < 26.

![image](https://user-images.githubusercontent.com/71587/190840494-6cfb7f6d-0cf9-42fd-bdd9-9762199168c6.png)

I think we can formulate a plan for dropping support for these versions. The 2022 survey is in the works, so it'll be worthwhile looking at that data before any decisions are final.

- - -

@magnars side note, can we open the Github discussion module for this sort of conversation.

**Comment by magnars** [comment]
No, we do not drop support without a very good reason to do so. Also, 6% is way too big a percentage for a package that is used by so many people.

**Comment by jasonm23** [comment]
Suggest we see what the 2022 survey shows us. What percentage would you considered negligable?

I'll ensure v24 is specifically included in the survey.

**Comment by magnars** [comment]
Dropping support for no specific reason? That would take 0%.

**Comment by jasonm23** [comment]
Obviously that can't be determined by a survey, due to the inherent failure of any survey to gain 100% participation.

If there's a specific technical issue that makes supporting a legacy version, intractible I'll consider that grounds and raise a separate issue.
