### ISSUE TITLE
Empty vs. blank

### ISSUE THREAD

**Issue by rejeep** [magnars/s.el#47]
Writing `s-presence` and `s-present?` made me think. I think s should change the definition of `s-blank?`.

I consider the string `"    "` to be blank, but not empty. Right now, it is not blank.

This is the spec I'm proposing:

**s-empty?**

``` lisp
(s-empty? "") ;; => t
(s-empty? nil) ;; => t
(s-empty? " ") ;; => nil
(s-empty? "    ") ;; => nil
(s-empty? "foo") ;; => nil
```

**s-blank?**

``` lisp
(s-blank? "") ;; => t
(s-blank? nil) ;; => t
(s-blank? " ") ;; => t
(s-blank? "    ") ;; => t
(s-blank? "foo") ;; => nil
```

**s-present? (aka. !s-blank?)**

``` lisp
(s-present? "") ;; => nil
(s-present? nil) ;; => nil
(s-present? " ") ;; => nil
(s-present? "    ") ;; => nil
(s-present? "foo") ;; => t
```

_(These changes are breaking and I'm not sure if you are planning to release a new major any time soon)_

**Comment by Wilfred** [comment]
I agree, it would be nice to have this. If we don't want to break backwards compatibility, we could define an `s-whitespace?` function.

**Comment by odanoburu** [comment]
I support this idea! any updates since then?

**Comment by jasonm23** [comment]
I'll add an `s-only-whitespace?` and `s-only-whitespace-p` to keep the API unequivocal.
