### ISSUE TITLE
s-replace-regex?

### ISSUE THREAD

**Issue by Silex** [magnars/s.el#49]
Hello,

Hum, I was surprised not to find this function (or `s-replace-all-regex`).

Is this intentional? I'll use `replace-regexp-in-string` in the meantime but I think it would make a nice addition :)

**Comment by salamynder** [comment]
May I ask why this is closed? I always forget that s-replace is quoting the regex....

**Comment by Silex** [comment]
Issue made in 2013, no comments after 6 months... didn't seem worth keeping open. If you want I can reopen it and ping magnars.

**Comment by salamynder** [comment]
:+1:

**Comment by salamynder** [comment]
maybe it's silly, I don't know, but when acting on strings with a string library, regex are quite handy, especially when replacing...

**Comment by Silex** [comment]
@magnars :blush:

**Comment by magnars** [comment]
Add the aliases in a PR and ping me, and I'll happily include it. Don't forget adding examples. :+1:

**Comment by Silex** [comment]
Alright, let's continue in #116
