### ISSUE TITLE
[discussion] Add functions for manipulation of text properties?

### ISSUE THREAD

**Issue by Fuco1** [magnars/s.el#65]
Is this something that would fit the library? Do we want it to be only string manipulation or _emacs string_ manipulation.  Text properties are very central to how emacs works with text, so I think it would fit all right, but maybe someone has a different opinion?

The emacs api for this is, as usual, absolutely terrible.  There's also a bunch of very useful functions in `gnus` namespace (as usual :D) which could be ported too (also `notmuch`, `eimp`, `org`, message`,`dired`... really, this is insane)

Maybe we can do it the same way as with `dash-functional`, leaving it in the same repo, but a separate file, for example `stp.el` (s-text-properties).  

Discuss.

**Comment by jasonm23** [comment]
Closing
