### ISSUE TITLE
Some unexpected results of s-truncate

### ISSUE THREAD

**Issue by politza** [magnars/s.el#71]
```
(s-truncate 2 "Albuquerque") => "Albuquerqu..."
(s-truncate 2 "Ohio") => "Ohi..."
(s-truncate 0 "Ohio") => "O..."
(s-truncate 1 "Ox") => "..."
(s-truncate 0 "Ox") => args-out-of-range
```

All these results seem unexpected to me.

**Comment by magnars** [comment]
Yeah, those are weird. Given the functionality of s-truncate, what would you expect?

**Comment by politza** [comment]
Signal `args-out-of-range` if `LEN` is negative; otherwise I'd suggest returning 0-2 dots.
