### ISSUE TITLE
feature request: add function inverse to `string-to-list`.

### ISSUE THREAD

**Issue by Fuco1** [magnars/s.el#73]
Add a function inverse to `string-to-list`.

Currently, one must do `(apply 'string list)` which is less than ideal in case we want to map or compose the (proposed, non existing) `list-to-string` function.

Could be called `s-list-to-string` or just `s-to-string`.

Awesome task for beginners :) !!!

**Comment by Fuco1** [comment]
Apparently `concat` does this... it might still warrant an alias because `concat` is totally undiscoverable when one wants to create a string from list of characters.

**Comment by wasamasa** [comment]
s.el doesn't have `s-string-to-list` or `s-to-list`...

**Comment by jasonm23** [comment]
Am I missing something? Isn't this `s-split` ?

**Comment by Fuco1** [comment]
I wanted a function doing this:

    (string-to-list "hello")       ;; => (104 101 108 108 111)
    ;; inverse function
    (concat (list ?h ?e ?l ?l ?o)) ;; => "hello"

**Comment by jasonm23** [comment]
Let's call it something more specific, how about `s-to-chars` or `s-to-charlist` ... something like that.

**Comment by jasonm23** [comment]
```lisp
(defun s-chars (s)
 "split S into a list of chars."
 (mapcar 
   (lambda (it) (string-to-char it)) 
   (s-split "" s))
```

something like that

**Comment by jasonm23** [comment]
Or ...

```
(defun s-chars (s)
 "split S into a list of chars."
 (mapcar 'string-to-char (s-split "" s))
```

**Comment by jasonm23** [comment]
```lisp
(defexamples s-to-chars ()
  "Test splitting a string into a list of chars."
  (s-chars "hellloooo") => (0 104 101 108 108 108 111 111 111 111 0))
```

**Comment by jasonm23** [comment]
The inverse...

```lisp
(s-from-chars (chars) ... 
;; or
(s-to-string (chars) ... 
```
The second one works best for me, the signature is telegraphing the source type. It's clear.

```lisp
(defun s-to-string (chars)
  "Convert a list of CHARS to a string."
  (concat chars))
```

```lisp
(defexamples s-to-string ()
  "Test char list to string conversion."
  (s-to-string '(104 101 108 108 111)) => "hello")
```

No nil problems this way around.

**Comment by jasonm23** [comment]
I can integrate these tomorrow.

**Comment by Fuco1** [comment]
`string-to-list` is a built-in which does this.  You don't need to implement it.

This issue was only to provide an `s` api to that and the inverse function, which is also built in (`concat`).

**Comment by jasonm23** [comment]
> You don't need to implement it.

The inverse is for symmetric integrity of the API (towards the goal of discoverable functionality.)

Is a PR coming?

**Comment by jasonm23** [comment]
Closing
