### ISSUE TITLE
Feature request: add an analogy of `strstr`

### ISSUE THREAD

**Issue by Fuco1** [magnars/s.el#76]
A function which given a string and a pattern should return the first index where the pattern matches or nil on failure.

Avoids useless wrapping in `save-matck-data` and calls to inspect the state...

api could be like

```
(s-match-position string regexp)
(s-match-position-all string regexp)
```

A good entry-level patch, for people interested in trying emacs lisp.

**Comment by wasamasa** [comment]
`s-index-of` sort of does that, but not for regular expressions.

**Comment by xiongtx** [comment]
Isn't this just `string-match-p`?

**Comment by Fuco1** [comment]
Does seems to, except there is no "all" variant.  We can alias the first.

**Comment by basil-conto** [comment]
@Fuco1 Does `s-matched-positions-all` cover the "all" variant? If not, could you please describe its intended behaviour?

**Comment by Fuco1** [comment]
@basil-conto Yes, that seems to implement the same idea.  I think we're good to close here then :)
