### ISSUE TITLE
optional argument omit-nulls for s-lines ?

### ISSUE THREAD

**Issue by sindikat** [magnars/s.el#86]
On GNU/Linux text files usually have trailing newlines. This newlines prove to be a nuisance every time all I want is to just break the contents of a file into lines. I instead use `(s-split "[\n\r]" some-text t)` and have this regex for compatibility over OSes. Maybe `s-lines` should have an optional omit-nulls argument? Or should [`f.el`](https://github.com/rejeep/f.el)'s `f-read-text` have an optional omit-trailing-newline argument instead?

_EDIT:_ Ok, there's `s-chomp` for removing trailing newlines, keep forgetting that.

**Comment by xiongtx** [comment]
Xah Lee has a [good tutorial](http://ergoemacs.org/emacs/elisp_read_file_content.html) on reading the contents of a file as lines.
