### ISSUE TITLE
s-join variant with beginning and end

### ISSUE THREAD

**Issue by fommil** [magnars/s.el#96]
scala's `mkString` function takes three parameters: `begin` `sep` `end` which means a list can be converted into `[foo,bar]` very easily. Such a function would be a great addition to this library!

**Comment by magnars** [comment]
Is it a real improvement over:

```
(s-with '("foo" "bar" "baz")
  (s-join ", ")
  (s-prepend "[")
  (s-append "]"))
```

?

**Comment by fommil** [comment]
probably not :smile: I guess I not thinking lispy enough

**Comment by fommil** [comment]
I think I've been doing

```
(append "[" (s-join ", " ... ) "]")
```

and that feels clunky.
